export const categoriasLibros = [
    {
        id: 1,
        nombre: "El retrato de Dorian Gray",
        autor: "Oscar Wilde",
        descripcion: "Un joven mantiene su juventud mientras su retrato envejece y refleja sus pecados.",
        anio: 1890,
        precio: 15000,
        cantidad: 25,
        categoria: "Drama",
        imagen: "https://covers.openlibrary.org/b/id/8308796-L.jpg"
    },
    {
        id: 2,
        nombre: "Los tres mosqueteros",
        autor: "Alexandre Dumas",
        descripcion: "Las aventuras de un joven que se une a los mosqueteros del rey en el siglo XVII.",
        anio: 1844,
        precio: 17000,
        cantidad: 20,
        categoria: "Aventura",
        imagen: "https://covers.openlibrary.org/b/id/8217096-L.jpg"
    },
    {
        id: 3,
        nombre: "Drácula",
        autor: "Bram Stoker",
        descripcion: "La historia del conde Drácula y su intento de mudarse a Inglaterra para expandir su influencia.",
        anio: 1897,
        precio: 18000,
        cantidad: 15,
        categoria: "Terror",
        imagen: "https://covers.openlibrary.org/b/id/7906793-L.jpg"
    },
    {
        id: 4,
        nombre: "El guardián entre el centeno",
        autor: "J.D. Salinger",
        descripcion: "Un adolescente en Nueva York narra su vida después de ser expulsado de la escuela.",
        anio: 1951,
        precio: 16000,
        cantidad: 30,
        categoria: "Ficción",
        imagen: "https://covers.openlibrary.org/b/id/7884945-L.jpg"
    },
    {
        id: 5,
        nombre: "Cumbres borrascosas",
        autor: "Emily Brontë",
        descripcion: "Una historia de amor y venganza en un páramo británico aislado.",
        anio: 1847,
        precio: 19000,
        cantidad: 12,
        categoria: "Romántico",
        imagen: "https://covers.openlibrary.org/b/id/8122825-L.jpg"
    },
    {
        id: 6,
        nombre: "Crónica de una muerte anunciada",
        autor: "Gabriel García Márquez",
        descripcion: "La historia de un asesinato anunciado que ocurre en un pequeño pueblo.",
        anio: 1981,
        precio: 14500,
        cantidad: 22,
        categoria: "Misterio",
        imagen: "https://covers.openlibrary.org/b/id/8250174-L.jpg"
    },
    {
        id: 7,
        nombre: "El libro de la selva",
        autor: "Rudyard Kipling",
        descripcion: "Las aventuras de Mowgli, un niño criado por lobos en la selva india.",
        anio: 1894,
        precio: 15500,
        cantidad: 18,
        categoria: "Aventura",
        imagen: "https://covers.openlibrary.org/b/id/8138467-L.jpg"
    },
    {
        id: 8,
        nombre: "La insoportable levedad del ser",
        autor: "Milan Kundera",
        descripcion: "Una novela filosófica sobre la libertad y el amor durante la Primavera de Praga.",
        anio: 1984,
        precio: 17500,
        cantidad: 14,
        categoria: "Filosofía",
        imagen: "https://covers.openlibrary.org/b/id/8235294-L.jpg"
    },
    {
        id: 9,
        nombre: "Mujercitas",
        autor: "Louisa May Alcott",
        descripcion: "La historia de cuatro hermanas que crecen durante la Guerra Civil en Estados Unidos.",
        anio: 1868,
        precio: 14000,
        cantidad: 30,
        categoria: "Clásico",
        imagen: "https://covers.openlibrary.org/b/id/8103791-L.jpg"
    },
    {
        id: 10,
        nombre: "El lobo estepario",
        autor: "Hermann Hesse",
        descripcion: "La lucha interna de un hombre que busca su verdadera identidad en una sociedad moderna.",
        anio: 1927,
        precio: 16500,
        cantidad: 10,
        categoria: "Filosofía",
        imagen: "https://covers.openlibrary.org/b/id/8234846-L.jpg"
    },
    {
        id: 11,
        nombre: "Fahrenheit 451",
        autor: "Ray Bradbury",
        descripcion: "En un futuro distópico, los bomberos queman libros para mantener el control social.",
        anio: 1953,
        precio: 18000,
        cantidad: 20,
        categoria: "Ciencia ficción",
        imagen: "https://covers.openlibrary.org/b/id/8217278-L.jpg"
    },
    {
        id: 12,
        nombre: "La naranja mecánica",
        autor: "Anthony Burgess",
        descripcion: "Un joven en un futuro distópico enfrenta el dilema del libre albedrío y la violencia.",
        anio: 1962,
        precio: 19000,
        cantidad: 16,
        categoria: "Ciencia ficción",
        imagen: "https://covers.openlibrary.org/b/id/8216470-L.jpg"
    },
    {
        id: 13,
        nombre: "El hombre invisible",
        autor: "H.G. Wells",
        descripcion: "La historia de un científico que descubre cómo volverse invisible y los efectos de su descubrimiento.",
        anio: 1897,
        precio: 15000,
        cantidad: 25,
        categoria: "Ciencia ficción",
        imagen: "https://covers.openlibrary.org/b/id/7735705-L.jpg"
    },
    {
        id: 14,
        nombre: "El silmarillion",
        autor: "J.R.R. Tolkien",
        descripcion: "Una colección de mitos y leyendas que preceden a El señor de los anillos.",
        anio: 1977,
        precio: 22000,
        cantidad: 8,
        categoria: "Fantasía",
        imagen: "https://covers.openlibrary.org/b/id/8238031-L.jpg"
    },
    {
        id: 15,
        nombre: "La caverna",
        autor: "José Saramago",
        descripcion: "Una alegoría sobre la realidad y la percepción en una sociedad moderna.",
        anio: 2000,
        precio: 17000,
        cantidad: 20,
        categoria: "Filosofía",
        imagen: "https://covers.openlibrary.org/b/id/8122786-L.jpg"
    },
    {
        id: 16,
        nombre: "Un mundo feliz",
        autor: "Aldous Huxley",
        descripcion: "Una visión distópica de una sociedad donde la estabilidad es mantenida a través de la manipulación y el condicionamiento.",
        anio: 1932,
        precio: 18500,
        cantidad: 15,
        categoria: "Ciencia ficción",
        imagen: "https://covers.openlibrary.org/b/id/8009124-L.jpg"
    },
    {
        id: 17,
        nombre: "La ladrona de libros",
        autor: "Markus Zusak",
        descripcion: "La historia de una niña que encuentra consuelo en los libros durante la Segunda Guerra Mundial.",
        anio: 2005,
        precio: 20000,
        cantidad: 12,
        categoria: "Drama",
        imagen: "https://covers.openlibrary.org/b/id/8043300-L.jpg"
    },
    {
        id: 18,
        nombre: "La vida de Pi",
        autor: "Yann Martel",
        descripcion: "La odisea de un joven náufrago y su supervivencia en el océano con un tigre de Bengala.",
        anio: 2001,
        precio: 21000,
        cantidad: 10,
        categoria: "Aventura",
        imagen: "https://covers.openlibrary.org/b/id/8262581-L.jpg"
    },
    {
        id: 19,
        nombre: "El nombre del viento",
        autor: "Patrick Rothfuss",
        descripcion: "La vida de Kvothe, un joven prodigio que se convierte en un héroe legendario.",
        anio: 2007,
        precio: 23000,
        cantidad: 14,
        categoria: "Fantasía",
        imagen: "https://covers.openlibrary.org/b/id/8286375-L.jpg"
    },
    {
        id: 20,
        nombre: "La sombra del viento",
        autor: "Carlos Ruiz Zafón",
        descripcion: "Un joven descubre un libro en un cementerio de libros olvidados y se ve envuelto en un misterio.",
        anio: 2001,
        precio: 22000,
        cantidad: 18,
        categoria: "Misterio",
        imagen: "https://covers.openlibrary.org/b/id/8216448-L.jpg"
    },
    {
        id: 21,
        nombre: "El código Da Vinci",
        autor: "Dan Brown",
        descripcion: "Un thriller sobre un secreto oculto en el arte y la historia que podría cambiar la humanidad.",
        anio: 2003,
        precio: 19000,
        cantidad: 20,
        categoria: "Thriller",
        imagen: "https://covers.openlibrary.org/b/id/8162784-L.jpg"
    },
    {
        id: 22,
        nombre: "Matar a un ruiseñor",
        autor: "Harper Lee",
        descripcion: "Una historia sobre la justicia y el racismo en el sur de los Estados Unidos.",
        anio: 1960,
        precio: 16000,
        cantidad: 25,
        categoria: "Drama",
        imagen: "https://covers.openlibrary.org/b/id/8170074-L.jpg"
    },
    {
        id: 23,
        nombre: "El Principito",
        autor: "Antoine de Saint-Exupéry",
        descripcion: "Un cuento filosófico sobre un joven príncipe que viaja de planeta en planeta.",
        anio: 1943,
        precio: 14000,
        cantidad: 30,
        categoria: "Fábula",
        imagen: "https://covers.openlibrary.org/b/id/7983286-L.jpg"
    },
    {
        id: 24,
        nombre: "Los pilares de la Tierra",
        autor: "Ken Follett",
        descripcion: "Una saga histórica sobre la construcción de una catedral en la Edad Media.",
        anio: 1989,
        precio: 25000,
        cantidad: 10,
        categoria: "Histórico",
        imagen: "https://covers.openlibrary.org/b/id/8193760-L.jpg"
    },
    {
        id: 25,
        nombre: "Beloved",
        autor: "Toni Morrison",
        descripcion: "La historia de una mujer esclava que regresa a su hogar con un pasado traumático.",
        anio: 1987,
        precio: 23000,
        cantidad: 15,
        categoria: "Drama",
        imagen: "https://covers.openlibrary.org/b/id/8306718-L.jpg"
    },
    {
        id: 26,
        nombre: "Un día en la vida de Ivan Denisovich",
        autor: "Aleksandr Solzhenitsyn",
        descripcion: "La historia de un prisionero en un campo de trabajo soviético durante el régimen estalinista.",
        anio: 1962,
        precio: 17500,
        cantidad: 12,
        categoria: "Drama",
        imagen: "https://covers.openlibrary.org/b/id/8097890-L.jpg"
    },
    {
        id: 27,
        nombre: "La chica del tren",
        autor: "Paula Hawkins",
        descripcion: "Un thriller psicológico sobre una mujer que se involucra en la desaparición de una mujer.",
        anio: 2015,
        precio: 21000,
        cantidad: 14,
        categoria: "Thriller",
        imagen: "https://covers.openlibrary.org/b/id/8322160-L.jpg"
    },
    {
        id: 28,
        nombre: "Cien años de soledad",
        autor: "Gabriel García Márquez",
        descripcion: "La historia de la familia Buendía a lo largo de siete generaciones en el pueblo ficticio de Macondo.",
        anio: 1967,
        precio: 28000,
        cantidad: 8,
        categoria: "Realismo mágico",
        imagen: "https://covers.openlibrary.org/b/id/8207580-L.jpg"
    },
    {
        id: 29,
        nombre: "Guerra y paz",
        autor: "León Tolstói",
        descripcion: "Una épica novela sobre la invasión napoleónica en Rusia y las vidas entrelazadas de varias familias.",
        anio: 1869,
        precio: 29000,
        cantidad: 6,
        categoria: "Histórico",
        imagen: "https://covers.openlibrary.org/b/id/8044570-L.jpg"
    },
    {
        id: 30,
        nombre: "Los juegos del hambre",
        autor: "Suzanne Collins",
        descripcion: "Una distopía en la que los jóvenes luchan en un torneo mortal para el entretenimiento de los ricos.",
        anio: 2008,
        precio: 20000,
        cantidad: 20,
        categoria: "Ciencia ficción",
        imagen: "https://covers.openlibrary.org/b/id/7998582-L.jpg"
    }
]
